import type { NextPage } from 'next'
import Head from 'next/head'

import Dashboard from '../../src/skins/paperbase/Dashboard'

import * as settings from '../../src/settings'
const PageName = "Dashboard - Overview"

const Page: NextPage = () => {
    return (
        <>
            <Head>
                <title>{settings.sitename} - {PageName}</title>
                <meta name="description" content="Generated by Ike" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Dashboard title={PageName} sitename={settings.sitename} navigation={settings.navigation}>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fatebuntur Stoici haec omnia dicta esse praeclare, neque eam causam Zenoni desciscendi fuisse. Tibi hoc incredibile, quod beatissimum. Quis enim redargueret? At enim, qua in vita est aliquid mali, ea beata esse non potest. Duo Reges: constructio interrete. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. Ita ne hoc quidem modo paria peccata sunt. Quid ergo attinet gloriose loqui, nisi constanter loquare? Graecum enim hunc versum nostis omnes-: Suavis laborum est praeteritorum memoria. </p>
                <p>Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. Quam ob rem tandem, inquit, non satisfacit? Qui enim existimabit posse se miserum esse beatus non erit. Suo genere perveniant ad extremum; Summus dolor plures dies manere non potest? </p>
                <p>Equidem, sed audistine modo de Carneade? Iam doloris medicamenta illa Epicurea tamquam de narthecio proment: Si gravis, brevis; Eadem nunc mea adversum te oratio est. Suam denique cuique naturam esse ad vivendum ducem. Claudii libidini, qui tum erat summo ne imperio, dederetur. </p>
                <p>Non enim quaero quid verum, sed quid cuique dicendum sit. Quae diligentissime contra Aristonem dicuntur a Chryippo. Itaque et manendi in vita et migrandi ratio omnis iis rebus, quas supra dixi, metienda. Quae quidem sapientes sequuntur duce natura tamquam videntes; In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Commoda autem et incommoda in eo genere sunt, quae praeposita et reiecta diximus; Ergo hoc quidem apparet, nos ad agendum esse natos. Quid ei reliquisti, nisi te, quoquo modo loqueretur, intellegere, quid diceret? </p>
                <p>Sed venio ad inconstantiae crimen, ne saepius dicas me aberrare; De ingenio eius in his disputationibus, non de moribus quaeritur. Quid igitur dubitamus in tota eius natura quaerere quid sit effectum? Sed mehercule pergrata mihi oratio tua. Quid dubitas igitur mutare principia naturae? Tollenda est atque extrahenda radicitus. Mihi enim satis est, ipsis non satis. Sed quia studebat laudi et dignitati, multum in virtute processerat. </p>
                <p>Aeque enim contingit omnibus fidibus, ut incontentae sint. Ut enim consuetudo loquitur, id solum dicitur honestum, quod est populari fama gloriosum. Num igitur utiliorem tibi hunc Triarium putas esse posse, quam si tua sint Puteolis granaria? Isto modo, ne si avia quidem eius nata non esset. </p>
                <p>Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Age nunc isti doceant, vel tu potius quis enim ista melius? Polemoni et iam ante Aristoteli ea prima visa sunt, quae paulo ante dixi. Ut proverbia non nulla veriora sint quam vestra dogmata. An est aliquid, quod te sua sponte delectet? Haec para/doca illi, nos admirabilia dicamus. Simul atque natum animal est, gaudet voluptate et eam appetit ut bonum, aspernatur dolorem ut malum. </p>
                <p>Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. A villa enim, credo, et: Si ibi te esse scissem, ad te ipse venissem. Non autem hoc: igitur ne illud quidem. Virtutis, magnitudinis animi, patientiae, fortitudinis fomentis dolor mitigari solet. Pudebit te, inquam, illius tabulae, quam Cleanthes sane commode verbis depingere solebat. </p>
                <p>Pisone in eo gymnasio, quod Ptolomaeum vocatur, unaque nobiscum Q. Teneo, inquit, finem illi videri nihil dolere. Quamquam tu hanc copiosiorem etiam soles dicere. Praeclare Laelius, et recte sofñw, illudque vere: O Publi, o gurges, Galloni! es homo miser, inquit. Rationis enim perfectio est virtus; Erit enim mecum, si tecum erit. </p>
            </Dashboard>
        </>
    )
}

export default Page
